- conf: NSF Proposal Evaluation 2021
  type: Panelist
  role: service-reviewing
  
- conf: ICRA Debates 2021
  type: Co-Organizer
  role: service-organizing
  
- conf: Frontiers 2021
  type: Topic Editor
  role: service-reviewing
  
- conf: HRI 2021
  type: SDC Co-Chair
  role: service-organizing
  
- conf: RSS 2021
  type: Publicity Chair
  role: service-organizing
  
- conf: Pioneers RSS 2021
  type: General Chair
  role: service-organizing
